***


# Emerging Technology Tasks


***
This Juypter Notebook is a collection of solutions to the tasks given to me for the Emerging Technology module delivered by Dr. Ian Mcloughlin. Each of the four tasks are marked below. You will also find a list of references.

Author: Darragh Lally   
GMIT ID: G00220290   
Mail: g00220290@gmit.ie

***

## Task 1: SQRT2

***

In the first of our tasks we are to create a python function that will compute and display the square root of 2, to 100 decimal places **without** using any extra imports, including but not limited to math.   


Using Newton's Method we can calculate the square root of a number [1.1]. To find the square root $z$ of number $x$, we can loop using the following;   
    
$$ z_{next} = z - \frac{z^2 - x}{2z} $$    


***
#### Step 1
***
Using Newtons method to calculate the square root of 2. Testing our algorithm with number '2' against the import 'math', we can confirm the algorithm is returning an acceptable value. But we are seeing a limited number of decimal places. The problem calls for us to print the value to one hundred decimal places. Which leads us to the next step.

#### Newtons Method in Python

In [1]:
def sqrt2(x):
    """
    A function to calculate the square root of a number. 
    """
    # Inital guess for sqrt of z
    z = x / 2     
    # Loop until happy with accuracy
    while abs(x - (z * z)) > 0.0001:
        # Calculate a better guess
        z -= (z*z - x) / (2*z)
    # Return the approx square root of x
    return z

#### Testing

In [2]:
# Test our function
sqrt2(2)

1.4142156862745099

In [3]:
# Now with the 'math' equivalent
import math
math.sqrt(2)

1.4142135623730951

***
#### Step 2
***
**2.1** We need to now figure out how to print out more decimal places, currently we have 15. One post on stackoverflow[1.2] suggests using the function repr() [1.3].
- repr(); This function returns a string representation of an object been passed as the parameter.
- Below test shows that repr() is returning the same number of decimal places as before.
    - This result suggests that under the hood the number is been stored to 15 decimal places and not just printing that number for readability.
    
#### Testing

In [4]:
# Testing repr()
ans = sqrt2(2)
print('With repr(): ')
print( repr(ans))
print('Without repr(): ')
print(ans)

With repr(): 
1.4142156862745099
Without repr(): 
1.4142156862745099


**2.2** The same stackoverflow post [1.2], also suggests trying to format the string output using the following;
- "{0:.100f}".format(a), where the float value is the number of decimal places.
    - We are getting closer to our solution as seen by the extra accuracy of our output, yet the trailing zeros should be addressed.
    
#### Testing

In [5]:
# Testing string formatting
ans = sqrt2(2)
"{0:.100f}".format(ans)

'1.4142156862745098866440685014822520315647125244140625000000000000000000000000000000000000000000000000'

**2.3** Another post on stackoverflow. 
https://stackoverflow.com/questions/5187664/generating-digits-of-square-root-of-2
Function returns the square root of 'a' with 'digits' number of places.It does not however place the decimal point in its output. 

In [6]:
# https://stackoverflow.com/questions/5187664/generating-digits-of-square-root-of-2
def sqroot(a, digits):
    a = a * (10**(2*digits))
    x_prev = 0
    x_next = 1 * (10**digits)
    while x_prev != x_next:
        x_prev = x_next
        x_next = (x_prev + (a // x_prev)) >> 1
    return x_next
print(sqroot(2,100))

14142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


**2.4** Refactoring the above function to meet my needs. This will prove my understanding of the function but also allow me to add the decimal point into the output. Although the problem calls for us to deal with 2 to 100 places, I am leaving the function parameters, so we can perform this square root on any number passed in and, be able to decide the number of digits returned in each case.

In [7]:
# 1.0 Multiply n, by 10 to the power of 2 times d
# n = number to preform square root on
# d = number of digits to return

# 2.0 Find square root of n
def sqrt2(n,d):
    n = n*(10**(2*d))
    x_previous = 0
    x_next = 1*(10**d)
    while x_previous != x_next:
        x_previous = x_next
        x_next = (x_previous + (n//x_previous)) >> 1
    return x_next

#### Testing

In [8]:
print(sqrt2(2,100))

14142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


### References; sqrt2
[1.1] A tour of Go; Exercise: Loops and Functions; https://tour.golang.org/flowcontrol/8

[1.2] stackeoverflow, more decimal places needed in python; https://stackoverflow.com/questions/14057835/more-decimal-places-needed-in-python

[1.3] repr(), Programiz, Python Tutorials; https://www.programiz.com/python-programming/methods/built-in/repr

***
## Task 2: Chi-squared  $\chi^2$
***
Our second task is to verify the Chi-squared value from a given table of data. Published by Karl Pearson in 1900, it is considerd to be a 'founding stone' of moders statistics[2.1].

#### Given Table - [2.1]
| | A | B | C | D | Total     
| :------------- | :----------: | :-----------: | :-----------: | :-----------: | -----------: |
|  White Collar | 90 | 60 | 104 | 95 | 349 |
| Blue Collar | 30 | 50 | 51 | 20 | 151 |
| No Collar | 30 | 40 | 45 | 35 | 150 |
| Total | 150 | 150 | 200 | 150 | 650 |


#### Value to be verified
Approximately **24.6**

In [9]:
import numpy as np
import pandas as pd
import scipy.stats as stats

cols = ['A', 'B', 'C', 'D']
data = pd.DataFrame(columns=cols)

data.loc['White Collar'] = [90, 60, 104, 95]
data.loc['Blue Collar'] = [30, 50, 51, 20]
data.loc['No collar'] = [30, 40, 45, 35]

print(data)

               A   B    C   D
White Collar  90  60  104  95
Blue Collar   30  50   51  20
No collar     30  40   45  35


In [10]:
V, p, dof, expected = stats.chi2_contingency(data) 
# add correction=False for uncorrected Chi-square

print ('P value for effect of area on proportion of each collar:')
print (p)
print ('\nExpected numbers if area did not effect proportion of each collar:')
print (expected)

P value for effect of area on proportion of each collar:
0.0004098425861096696

Expected numbers if area did not effect proportion of each collar:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


# References

### General
Markdown mathematical symbols, LKS90 Github, https://gist.github.com/LKS90/252ac41bd4a173be35b0 

Markdown Guide, https://www.markdownguide.org/

### chi squared
[2.1] Chi-squared, wikipedia, https://en.wikipedia.org/wiki/Chi-squared_test