***
# Task Two
***
Below you will find my solution for the 'Chi-squared' task, an assessment for the Emerging Technology module delivered by Dr. Ian Mcloughlin.

Author: Darragh Lally   
GMIT ID: G00220290   
Mail: g00220290@gmit.ie

***
### Chi-squared  $\chi^2$
***
Our second task is to verify the Chi-squared value from a given table of data[1]. Published by Karl Pearson in 1900, it is considerd to be a 'founding stone' of moders statistics[1].

#### Given Table -
| | A | B | C | D | Total     
| :------------- | :----------: | :-----------: | :-----------: | :-----------: | -----------: |
|  White Collar | 90 | 60 | 104 | 95 | 349 |
| Blue Collar | 30 | 50 | 51 | 20 | 151 |
| No Collar | 30 | 40 | 45 | 35 | 150 |
| Total | 150 | 150 | 200 | 150 | 650 |


#### Value to be verified
Approximately **24.6**


In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

cols = ['A', 'B', 'C', 'D']
data = pd.DataFrame(columns=cols)

data.loc['White Collar'] = [90, 60, 104, 95]
data.loc['Blue Collar'] = [30, 50, 51, 20]
data.loc['No collar'] = [30, 40, 45, 35]

print(data)

               A   B    C   D
White Collar  90  60  104  95
Blue Collar   30  50   51  20
No collar     30  40   45  35


In [2]:
V, p, dof, expected = stats.chi2_contingency(data) 
# add correction=False for uncorrected Chi-square

print ('P value for effect of area on proportion of each collar:')
print (p)
print ('\nExpected numbers if area did not effect proportion of each collar:')
print (expected)

P value for effect of area on proportion of each collar:
0.0004098425861096696

Expected numbers if area did not effect proportion of each collar:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


# References

Markdown mathematical symbols, LKS90 Github, https://gist.github.com/LKS90/252ac41bd4a173be35b0 

Markdown Guide, https://www.markdownguide.org/

[1] Chi-squared, wikipedia, https://en.wikipedia.org/wiki/Chi-squared_test